name: Deploy Gatsby to GitHub Pages

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        description: "Version of Node.js to use.  Defaults to 16"
        default: '16'
    

env:
  PREFIX_PATHS: true gatsby build
  NODE_ENV: production
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This build job takes care of preparing the artifact that we'll deploy to Pages
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: paper-spa/gatsby-pages-build@main
      with:
        node-version: ${{ inputs.node-version }}

    - name: Upload Pages artifact
      uses: paper-spa/upload-pages-artifact@main
      with:
        directory: 'public'

  # The deploy job tells Pages to deploy the artifact we created in "build"
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
